apiVersion: apps/v1
kind: Deployment
metadata:
  name: cook
  namespace : istio-menu
  labels:
    app: cook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cook
  template:
    metadata:
      labels:
        app: cook
    spec:
      containers:
        - name: cook
          image: 281496546355.dkr.ecr.ap-northeast-1.amazonaws.com/tp-cook:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5